# COSINE SIMILARITY BETWEEN TWO DOCUMENTS

In [1]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
s1=["If you or someone in your household has mild to moderate respiratory illness or the key findings of coronavirus (fever, cough, malaise, or respiratory symptoms), isolation is required. "]
s2=["The patient MUST stay home except to get medical care – they must not go to work/school or interact with others outside the home until well (see the criteria in the ‘I’m Sick’ page). This is ‘Isolation’."]

In [3]:
vectorizer = CountVectorizer(stop_words='english')
vectorizer.fit(s1)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [4]:
print(vectorizer.vocabulary_)

{'household': 4, 'mild': 9, 'moderate': 10, 'respiratory': 12, 'illness': 5, 'key': 7, 'findings': 3, 'coronavirus': 0, 'fever': 2, 'cough': 1, 'malaise': 8, 'symptoms': 13, 'isolation': 6, 'required': 11}


In [5]:
vector = vectorizer.transform(s1)

In [6]:
print(vector.shape)
print(type(vector))
print(vector.toarray())
vec1=vector.toarray()

(1, 14)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 1 1 1 1 1 1 1 1 1 1 1 2 1]]


In [7]:
print(vectorizer.vocabulary_)

{'household': 4, 'mild': 9, 'moderate': 10, 'respiratory': 12, 'illness': 5, 'key': 7, 'findings': 3, 'coronavirus': 0, 'fever': 2, 'cough': 1, 'malaise': 8, 'symptoms': 13, 'isolation': 6, 'required': 11}


In [8]:
vector = vectorizer.transform(s2)
print(vector.toarray())
vec2=vector.toarray()


[[0 0 0 0 0 0 1 0 0 0 0 0 0 0]]


In [9]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vec1,vec2)

array([[0.24253563]])